from django.shortcuts import render, redirect
from os.path import isfile
from django.utils import timezone as tz

confile='conf.py'

# Create your views here.
def index(req):
	params=dict()
	if req.method=='POST':
		f=open(confile, 'w')
		f.write('#This file is generated by system to store the configuration\n')
		f.write('#Generated at %s\n'%tz.now().strftime('%Y-%m-%dT%H:%M:%S%z'))
		f.write('TOKEN=\'%s\'\n'%req.POST.get('token', ''))
		f.write('IPADDR=\'%s\'\n'%req.POST.get('ipaddr', ''))
		f.write('PORT=\'%s\'\n'%req.POST.get('port', ''))
		f.close()
		return redirect('index')

	if isfile(confile):
		exec(open(confile, 'r').read())
		if 'TOKEN' in locals(): params['TOKEN']=locals()['TOKEN']
		if 'IPADDR' in locals(): params['IPADDR']=locals()['IPADDR']
		if 'PORT' in locals(): params['PORT']=locals()['PORT']
	return render(req, 'gateway/index.html', params)

def cmd(req):
	pass
	return None
